CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "role" varchar,
  "created_at" timestamp
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "body" text NOT NULL,
  "user_id" integer NOT NULL,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "follows" (
  "following_user_id" integer NOT NULL,
  "followed_user_id" integer NOT NULL,
  "created_at" timestamp,
  PRIMARY KEY ("following_user_id", "followed_user_id")
);

COMMENT ON TABLE "users" IS 'Bảng lưu thông tin người dùng';

COMMENT ON COLUMN "users"."role" IS 'user or admin';

COMMENT ON TABLE "posts" IS 'Bảng lưu bài viết của người dùng';

COMMENT ON COLUMN "posts"."body" IS 'Content of the post';

COMMENT ON TABLE "follows" IS 'Bảng lưu quan hệ theo dõi giữa người dùng';

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("following_user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id");
