CREATE TABLE "genre" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "genre_name" "VARCHAR(50)" DEFAULT null,
  PRIMARY KEY ("id")
);

CREATE TABLE "publisher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "publisher_name" "VARCHAR(100)" DEFAULT null,
  PRIMARY KEY ("id")
);

CREATE TABLE "region" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "region_name" "VARCHAR(50)" DEFAULT null,
  PRIMARY KEY ("id")
);

CREATE TABLE "platform" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "platform_name" "VARCHAR(50)" DEFAULT null,
  PRIMARY KEY ("id")
);

CREATE TABLE "game" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "genre_id" INT DEFAULT null,
  "game_name" "VARCHAR(200)" DEFAULT null,
  PRIMARY KEY ("id")
);

CREATE TABLE "game_publisher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "game_id" INT DEFAULT null,
  "publisher_id" INT DEFAULT null,
  PRIMARY KEY ("id")
);

CREATE TABLE "game_platform" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "game_publisher_id" INT DEFAULT null,
  "platform_id" INT DEFAULT null,
  "release_year" INT DEFAULT null,
  PRIMARY KEY ("id")
);

CREATE TABLE "region_sales" (
  "region_id" INT DEFAULT null,
  "game_platform_id" INT DEFAULT null,
  "num_sales" "DECIMAL(5,2)" DEFAULT null
);

ALTER TABLE "game" ADD CONSTRAINT "fk_gm_gen" FOREIGN KEY ("genre_id") REFERENCES "genre" ("id");

ALTER TABLE "game_publisher" ADD CONSTRAINT "fk_gpu_gam" FOREIGN KEY ("game_id") REFERENCES "game" ("id");

ALTER TABLE "game_publisher" ADD CONSTRAINT "fk_gpu_pub" FOREIGN KEY ("publisher_id") REFERENCES "publisher" ("id");

ALTER TABLE "game_platform" ADD CONSTRAINT "fk_gpl_gp" FOREIGN KEY ("game_publisher_id") REFERENCES "game_publisher" ("id");

ALTER TABLE "game_platform" ADD CONSTRAINT "fk_gpl_pla" FOREIGN KEY ("platform_id") REFERENCES "platform" ("id");

ALTER TABLE "region_sales" ADD CONSTRAINT "fk_rs_gp" FOREIGN KEY ("game_platform_id") REFERENCES "game_platform" ("id");

ALTER TABLE "region_sales" ADD CONSTRAINT "fk_rs_reg" FOREIGN KEY ("region_id") REFERENCES "region" ("id");
